import { expect, test } from '@playwright/test'

// Navegación HTTP real, sin reemplazar fetch ni IndexedDB.
test('Flete: solicitud persistente, cotización y seguimiento en otra pestaña', async ({ page, context }) => {
  const errors: string[] = []
  const apiCalls: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (new URL(request.url()).pathname.includes('/api/')) apiCalls.push(request.url()) })
  await page.goto('demos/flete/')
  const start = page.locator('.hero-actions').getByRole('button', { name: 'Solicitar servicio', exact: true })
  await expect(start).toBeVisible()
  await expect(page.locator('.mode-banner')).toContainText('no se coordinan viajes reales')
  await expect(page.locator('.mode-banner')).not.toContainText('temporal')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual((page.viewportSize()?.width ?? 0) + 1)
  await start.click()
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByRole('button', { name: 'Completar con datos de ejemplo', exact: true }).click()
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.locator('#consent').check()
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Revisá tu solicitud.' })).toBeVisible()
  await page.getByRole('button', { name: 'Enviar solicitud', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Solicitud recibida.' })).toBeVisible()
  const code = await page.locator('.tracking-code strong').innerText()
  const token = new URL(page.url()).hash.split('/')[2]
  expect(token).toMatch(/^[a-f0-9]{64}$/)
  await page.reload()
  await expect(page.locator('.tracking-code strong')).toHaveText(code)
  await page.goto('demos/flete/#/seguimiento')
  await page.getByRole('link', { name: 'Abrir mi última solicitud' }).click()
  await expect(page.locator('.tracking-code strong')).toHaveText(code)
  await page.getByRole('button', { name: 'Gestionar en el panel', exact: true }).click()
  await expect(page.getByRole('heading', { name: code, exact: true })).toBeVisible()
  await page.locator('#quote-amount').fill('45000,50')
  await page.getByRole('button', { name: 'Guardar cotización', exact: true }).click()
  await expect(page.locator('.detail-heading .badge')).toContainText('Cotizada')
  await page.locator('#internal-note').fill('NOTA INTERNA QA NO PUBLICAR')
  await page.getByRole('button', { name: 'Guardar nota', exact: true }).click()
  await expect(page.locator('.notes-list')).toContainText('NOTA INTERNA QA NO PUBLICAR')
  const vehicle = await page.locator('#assign-vehicle option').filter({ hasText: 'Camioneta' }).first().getAttribute('value')
  if (!vehicle) throw new Error('No se encontró el vehículo de prueba')
  await page.locator('#assign-vehicle').selectOption(vehicle)
  await page.getByRole('button', { name: 'Confirmar servicio', exact: true }).click()
  await expect(page.locator('.detail-heading .badge')).toContainText('Confirmada')
  await page.reload()
  await expect(page.locator('.detail-heading .badge')).toContainText('Confirmada')
  const tracking = await context.newPage()
  await tracking.goto('demos/flete/#/seguimiento/' + token)
  await expect(tracking.locator('.tracking-code .badge')).toContainText('Confirmada')
  await expect(tracking.locator('.price-block')).toContainText('45.000,50')
  await expect(tracking.locator('.price-block')).toContainText('DATO DEMO')
  await expect(tracking.locator('.assigned-vehicle')).toContainText('VEHÍCULO DE EJEMPLO')
  await expect(tracking.locator('.assigned-vehicle')).toBeVisible()
  await expect(tracking.locator('body')).not.toContainText('NOTA INTERNA QA NO PUBLICAR')
  await tracking.close()
  await page.goto('demos/flete/#/admin/ajustes')
  await expect(page.locator('.environment-panel')).toContainText('IndexedDB en este navegador')
  await expect(page.locator('.environment-panel')).toContainText('Rol de demostración')
  await expect(page.locator('.environment-panel')).not.toContainText('Supabase')
  expect(apiCalls).toEqual([])
  expect(errors).toEqual([])
})

test('Flete: portada, recorrido rápido, FAQ, controles y CTA móvil', async ({ page }, testInfo) => {
  await page.goto('demos/flete/')
  await expect(page.locator('.quick-card')).toBeVisible()
  await expect(page.locator('#demo-controls')).toHaveCount(0)
  await expect(page.locator('.public-header')).not.toContainText('Panel')
  await page.screenshot({ path: testInfo.outputPath('home.png'), fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Mostrar controles de demostración' }).click()
  await expect(page.locator('#demo-controls')).toBeVisible()
  await page.getByRole('button', { name: 'Mostrar controles de demostración' }).click()
  await expect(page.locator('#demo-controls')).toHaveCount(0)
  if ((page.viewportSize()?.width ?? 1440) < 800) {
    await page.locator('#servicios').scrollIntoViewIfNeeded()
    await expect(page.locator('.mobile-request-bar')).toHaveClass('mobile-request-bar visible')
    await page.locator('#quick-origin').focus()
    await expect(page.locator('.mobile-request-bar')).not.toHaveClass('mobile-request-bar visible')
    await page.locator('#quick-origin').blur()
  }
  await page.locator('.faq-list summary').first().focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.faq-list details').first()).toHaveAttribute('open', '')
  await page.keyboard.press('Enter')
  await expect(page.locator('.faq-list details').first()).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'Continuar solicitud', exact: true }).click()
  await expect(page.locator('#quick-origin')).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('#quick-origin')).toBeFocused()
  await page.locator('#quick-origin').fill('Terminal de prueba')
  await page.locator('#quick-destination').fill('Terminal de prueba')
  await page.getByRole('button', { name: 'Continuar solicitud', exact: true }).click()
  await expect(page.locator('.quick-card .field-error').first()).toBeVisible()
  await page.locator('#quick-origin').fill('Origen de prueba')
  await page.locator('#quick-destination').fill('Destino de prueba')
  await page.locator('.quick-kind').getByRole('button', { name: 'Pasajeros', exact: true }).click()
  await page.getByRole('button', { name: 'Continuar solicitud', exact: true }).click()
  await expect(page.getByRole('heading', { name: '¿Cuándo lo necesitás?' })).toBeVisible()
  await expect(page.locator('.wizard-aside')).toContainText('Origen de prueba')
  await expect(page.locator('.wizard-aside')).toContainText('Traslado de pasajeros')
  await expect(page.locator('.mobile-request-bar')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '¿Cuándo lo necesitás?' })).toBeVisible()
  await expect(page.locator('.wizard-aside')).toContainText('Destino de prueba')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual((page.viewportSize()?.width ?? 0) + 1)
})

test('Flete: aceptación, concurrencia, recotización y confirmación diferenciadas', async ({ page, context }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('demos/flete/#/demo')
  await page.getByRole('button', { name: 'Ver ejemplo de seguimiento', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Aceptar cotización', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Gestionar en el panel', exact: true }).click()
  await expect(page.locator('#quote-amount')).toBeVisible()
  const adminURL = page.url()
  await page.getByRole('button', { name: 'Ver seguimiento del cliente', exact: true }).click()
  await page.getByRole('button', { name: 'Aceptar cotización', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Aceptar cotización', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Aceptar cotización', exact: true }).click()
  const operator = await context.newPage()
  await operator.goto(adminURL)
  await operator.locator('#quote-amount').fill('105000')
  await operator.getByRole('button', { name: 'Actualizar cotización', exact: true }).click()
  await expect(operator.locator('.quote-total')).toContainText('105.000')
  await page.getByRole('button', { name: 'Confirmar aceptación', exact: true }).click()
  await expect(page.locator('.public-notice')).toContainText('El importe cambió')
  await expect(page.locator('.accepted-receipt')).toHaveCount(0)
  await expect(page.locator('.price-block')).toContainText('105.000')
  await page.getByRole('button', { name: 'Aceptar cotización', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar aceptación', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Aceptaste la cotización.' })).toBeVisible()
  await expect(page.locator('.tracking-code .badge')).toContainText('Cotizada')
  await expect(page.locator('.assigned-vehicle')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.accepted-receipt')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('aceptada.png'), fullPage: true, animations: 'disabled' })
  await operator.reload()
  await expect(operator.locator('.operator-accepted')).toContainText('El cliente aceptó')
  await operator.goto('demos/flete/#/admin')
  await expect(operator.locator('.accepted-queue')).toBeVisible()
  await operator.goto(adminURL)
  await operator.locator('#quote-amount').fill('105000')
  await operator.getByRole('button', { name: 'Actualizar cotización', exact: true }).click()
  await expect(operator.locator('.operator-accepted')).toHaveCount(0)
  await page.getByRole('button', { name: 'Actualizar', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Aceptar cotización', exact: true })).toBeVisible()
  await expect(page.locator('.accepted-receipt')).toHaveCount(0)
  await operator.close()
  expect(errors).toEqual([])
})

test('Flete: recorrido guiado completo y sin desborde en 320px', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 600 })
  await page.goto('demos/flete/#/demo')
  await expect(page.getByRole('heading', { name: /Un traslado/i })).toBeVisible()
  await expect(page.locator('.demo-guide-disclaimer')).toHaveText('Recorrido demostrativo con datos ficticios.')
  await expect(page.locator('.demo-guide-notice')).toContainText('Ahora personalizamos servicios, vehículos, cobertura y forma de trabajo.')
  await expect(page.locator('.demo-guide-notice')).not.toContainText('IndexedDB')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(321)

  // Verificar que se listan los 9 pasos del ciclo comercial y operativo
  const stepItems = page.locator('.demo-flow-step')
  await expect(stepItems).toHaveCount(9)
  await expect(stepItems.first()).toContainText('Cliente pide')
  await expect(stepItems.last()).toContainText('Finaliza')

  // Probar acceso a inicio de solicitud como cliente
  await page.getByRole('button', { name: 'Probar una solicitud' }).click()
  await expect(page.getByRole('heading', { name: '¿Qué necesitás trasladar?' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(321)

  // Probar acceso al panel operativo
  await page.goto('demos/flete/#/demo')
  await page.getByRole('link', { name: 'Ver panel del dueño' }).click()
  await expect(page.getByRole('heading', { name: '¿Qué hay para resolver hoy?' })).toBeVisible()
  await expect(page.locator('.topbar-location')).toContainText('Panel de operaciones')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(321)
})
